/*
 * generated by Xtext 2.25.0
 */
package org.xtext.example.mydsl1.formatting2

import com.google.inject.Inject
import org.eclipse.xtext.formatting2.AbstractFormatter2
import org.xtext.example.mydsl1.services.MyDslGrammarAccess

class MyDslFormatter extends AbstractFormatter2 {
	
	@Inject extension MyDslGrammarAccess
	
}
